openapi: 3.1.0
info:
  title: User Apis
  version: 1.0.0
  description: API for managing user information.

paths:

  /auth/register:
    post:
      summary: Self-signup registration (public)
      operationId: registerUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDTO'
      responses:
        '201':
          description: User created
        '400':
          description: Invalid input
        '409':
          description: Email already registered

  /auth/login:
    post:
      summary: User login (public)
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentialsDTO'
      responses:
        '200':
          description: Login succeeded; returns JWT auth response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponseDTO'
        '401':
          description: Invalid credentials

  /auth/logout:
    post:
      summary: Invalidate current JWT (logout)
      operationId: logoutUser
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token revoked (client should discard it)
        '401':
          description: Unauthorized

  /me:
    get:
      summary: Get current logged-in user info
      operationId: getCurrentUser
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '401':
          description: Unauthorized

  /user/{id}:
    get:
      summary: Get user by ID
      operationId: getUserById
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found
    put:
      summary: Update user by ID
      operationId: updateUserById
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '404':
          description: User not found
        '400':
          description: Invalid input

  /user:
    post:
      summary: Create a new user (administrative)
      description: Administrative creation; requires appropriate role (e.g. ROLE_ADMIN).
      operationId: createUser
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        '400':
          description: Invalid input
        '403':
          description: Forbidden

  /user/{id}/disable:
    post:
      summary: Disable a user
      operationId: disableUser
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User disabled
        '404':
          description: User not found
        '403':
          description: Forbidden

  /user/{id}/enable:
    post:
      summary: Enable a user
      operationId: enableUser
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User enabled
        '404':
          description: User not found
        '403':
          description: Forbidden


  /auth/password/setup:
    post:
      summary: Initial password setup after registration (public)
      operationId: setupPassword
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetupPasswordDTO'
      responses:
        '201':
          description: Password set successfully
        '400':
          description: Invalid token or password rules violation

  /auth/password/reset:
    post:
      summary: Request password reset (public)
      operationId: requestPasswordReset
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequestDTO'
      responses:
        '200':
          description: Password reset email sent if account exists
        '400':
          description: Invalid input

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginCredentialsDTO:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string


    RegisterRequestDTO:
      type: object
      required:
        - email
        - firstName
        - lastName
        - phoneNumber
      properties:
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        branchRoles:
          type: array
          items:
            $ref: '#/components/schemas/BranchRoleDTO'

    BranchRoleDTO:
      type: object
      required:
        - bankCode
        - bankId
        - role
      properties:
        bankCode:
          type: string
        bankId:
          type: string
        role:
          type: string


    SetupPasswordDTO:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          description: "New password (apply server-side validation rules)"

    PasswordResetRequestDTO:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email

    PasswordResetConfirmDTO:
      type: object
      required:
        - token
        - password
      properties:
        token:
          type: string
          description: "Password reset token sent to user's email"
        password:
          type: string
          description: "New password (apply server-side validation rules)"

    AuthResponseDTO:
      type: object
      properties:
        token:
          type: string
        tokenType:
          type: string
        expiresIn:
          type: integer
          format: int64

    UserDTO:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        country:
          type: string
        city:
          type: string
        address:
          type: string
        gender:
          type: string
        birthDate:
          type: string
        userBranchRoles:
          type: array
          items:
            $ref: '#/components/schemas/UserBranchRoleDTO'
        userSettings:
          $ref: '#/components/schemas/UserSettingsDTO'

    UserBranchRoleDTO:
      type: object
      properties:
        bankCode:
          type: string
        role:
          type: string

    UserSettingsDTO:
      type: object
      properties:
        language:
          type: string
        theme:
          type: string
